### ISSUE TITLE
在首页的搜索这里有点BUG

### ISSUE THREAD

**Issue by fastgoo** [Thunf/wepy-demo-bookmall#3]
首页搜索栏，点击后可以输入信息，但是无法收起。
优化过后的代码：
```
<input type="text" class="weui-search-bar__input" placeholder="{{placeholder}}" value="{{inputVal}}" focus="{{inputShowed}}" @blur="hideInput" @input="inputTyping" confirm-type="search" @confirm="search"/>
```
失去焦点的时候调方法 hideInput ,把 inputShowed 设置为fase。为了交互体验可以把键盘右下角的完成建换成 搜索，通过confirm时间去让用户点击键盘上的搜索按钮去操作

**Comment by Thunf** [comment]
已更新 [commit f61c1a7](https://github.com/Thunf/wepy-demo-bookmall/commit/f61c1a70409420ff5cb5b9c677e23c96a0368807)，建议直接PR~ 

之前小程序input变换时超丑，不想搜索栏变来变去就没处理，目前看起来好多了，已经按你的issue调整了~~
